[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
dbgprint = "0.1.0"
iter_tools = "0.24.0"
ndarray = "0.16.1"
num-integer = "0.1.46"
petgraph = "0.6.5"
rand = "0.9.0-beta.1"
rayon = "1.10.0"
regex = "1.11.1"
